export const PlayerData = [
  {
    personId: 1,
    lastName: "Hiromitsu",
    firstName: "Kasahara",
    homeclub: "JP",
    usattNumber: 2796,
  },
  {
    personId: 2,
    lastName: "Sheng",
    firstName: "Xi",
    homeclub: "New York,",
    usattNumber: 2783,
  },
  {
    personId: 3,
    lastName: "Nikhil",
    firstName: "Kumar",
    homeclub: "San Jose, CA",
    rating: "Spartans Table Tennis Club",
    usattNumber: 2777,
  },
  {
    personId: 4,
    lastName: "Zhang",
    firstName: "Yu",
    homeclub: "N/A",
    usattNumber: 2770,
  },
  {
    personId: 5,
    lastName: "Thiago Farias",
    firstName: "Monteiro",
    homeclub: "FN",
    usattNumber: 2766,
  },
  {
    personId: 6,
    lastName: "Wenzhang",
    firstName: "Tao",
    homeclub: "Santa Clara, CA",
    rating: "Spartans Table Tennis Club",
    usattNumber: 2758,
  },
  {
    personId: 7,
    lastName: "Xin",
    firstName: "Zhou",
    homeclub: "Milpitas, CA",
    rating: "ICC Table Tennis Center",
    usattNumber: 2755,
  },
  {
    personId: 8,
    lastName: "Kentaro",
    firstName: "Miuchi",
    homeclub: "AI",
    usattNumber: 2745,
  },
  {
    personId: 9,
    lastName: "Kaden",
    firstName: "Xu",
    homeclub: "Dunellen, NJ",
    usattNumber: 2742,
  },
  {
    personId: 10,
    lastName: "Dimitrij",
    firstName: "Prokopcov",
    homeclub: "N/A",
    usattNumber: 2735,
  },
  {
    personId: 11,
    lastName: "Tomoya",
    firstName: "Fujimura",
    homeclub: "N/A",
    usattNumber: 2705,
  },
  {
    personId: 12,
    lastName: "Yi",
    firstName: "Liu",
    homeclub: "N/A",
    usattNumber: 2704,
  },
  {
    personId: 13,
    lastName: "Lei",
    firstName: "Kou",
    homeclub: "N/A",
    usattNumber: 2691,
  },
  {
    personId: 14,
    lastName: "Yinchi",
    firstName: "Fang",
    homeclub: "N/A",
    usattNumber: 2688,
  },
  {
    personId: 15,
    lastName: "Bob",
    firstName: "Chen",
    homeclub: "Sunnyvale, CA",
    usattNumber: 2688,
  },
  {
    personId: 16,
    lastName: "Jinbao",
    firstName: "Ma",
    homeclub: "Sunnyvale, CA",
    usattNumber: 2688,
  },
  {
    personId: 17,
    lastName: "Daniel",
    firstName: "Gorak",
    homeclub: "Queens, NY",
    usattNumber: 2683,
  },
  {
    personId: 18,
    lastName: "Jiwei",
    firstName: "Xu",
    homeclub: "Whippany, CA",
    usattNumber: 2681,
  },
  {
    personId: 19,
    lastName: "Yijun",
    firstName: "Feng",
    homeclub: "Long Island City, NY",
    rating: "Atlanta International Table Tennis Academy",
    usattNumber: 2680,
  },
  {
    personId: 20,
    lastName: "Ojo",
    firstName: "Onaolapo",
    homeclub: "Staten Island,",
    usattNumber: 2666,
  },
  {
    personId: 21,
    lastName: "Mingwei",
    firstName: "Ju",
    homeclub: "Milpitas,",
    usattNumber: 2665,
  },
  {
    personId: 22,
    lastName: "Enzo",
    firstName: "Angles",
    homeclub: "Vila Nova De Gaia,",
    usattNumber: 2657,
  },
  {
    personId: 23,
    lastName: "Hongtao",
    firstName: "Chen",
    homeclub: "Mississauga, CAN",
    usattNumber: 2654,
  },
  {
    personId: 24,
    lastName: "Chen Ce",
    firstName: "Wang",
    homeclub: "Kansas City,",
    usattNumber: 2648,
  },
  {
    personId: 25,
    lastName: "Jeremy",
    firstName: "Hazin",
    homeclub: "Richmond Hill,",
    usattNumber: 2646,
  },
];
